name: Export Gerbers (KiCad CLI)
on:
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect PCB
        id: f
        shell: bash
        run: |
          PCB=$(find . -maxdepth 3 -type f -name "*.kicad_pcb" | head -n1 || true)
          [ -z "$PCB" ] && echo "::error ::Upload file .kicad_pcb (valid KiCad 8/9) lalu run ulang" && exit 1
          echo "pcb=$PCB" >> $GITHUB_OUTPUT
      - name: Run KiCad actions (Gerber+Drill)
        uses: actions-for-kicad/kicad-actions@v1-k9.0
        with:
          pcb_file_name: ${{ steps.f.outputs.pcb }}
          run_drc: false
          pcb_output_gerbers_and_drill: true
          pcb_output_image: true
      - name: Zip & Upload
        shell: bash
        run: cd gerbers && zip -r ../Gerber_UniversalPowerBoard.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: Gerber_UniversalPowerBoard
          path: Gerber_UniversalPowerBoard.zip
