
name: Export Gerbers (KiCad CLI v1.0)

on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.kicad_pcb"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect KiCad PCB
        id: locate
        shell: bash
        run: |
          set -e
          PCB=$(find . -maxdepth 3 -type f -name "*.kicad_pcb" | head -n1 || true)
          if [ -z "$PCB" ]; then
            echo "::error ::No .kicad_pcb found. Upload the KiCad board then run again."; exit 1
          fi
          echo "pcb=$PCB" >> $GITHUB_OUTPUT

      - name: Run KiCad actions (Gerber + Drill)
        uses: actions-for-kicad/kicad-actions@v1-k9.0
        with:
          pcb_file_name: ${{ steps.locate.outputs.pcb }}
          run_drc: false
          pcb_output_gerbers_and_drill: true
          pcb_output_image: true

      - name: Zip outputs
        shell: bash
        run: |
          test -d gerbers || (echo "::error ::Gerbers folder missing. Check KiCad log above."; exit 1)
          cd gerbers
          zip -r ../UPB_v1p0_Gerber_Final.zip .
          cd ..
          ls -lah UPB_v1p0_Gerber_Final.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UPB_v1p0_Gerber_Final
          path: UPB_v1p0_Gerber_Final.zip
