
name: Publish Included Gerber ZIP (v2)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify included Gerber ZIP
        run: |
          test -f fabrication/UPB_Gerber_v0p2_protel.zip || (echo 'Gerber ZIP missing'; exit 1)
          ls -lah fabrication

      - name: Upload artifact (Gerber ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: Gerber_UniversalPowerBoard
          path: fabrication/UPB_Gerber_v0p2_protel.zip
